FILES = \
Graphics/MyCanvas.java  Graphics/MickeySoln.java  Graphics/cardset.zip \
Graphics/Mickey.java        Graphics/Moire.java       Graphics/CardTable.java \
MyGridWorld/BoxBug.java           MyGridWorld/GoodTermite.java \
MyGridWorld/BoxBugRunner.java     MyGridWorld/LangtonRunner.java \
MyGridWorld/BugRunner.java        MyGridWorld/LangtonTermite.java \
MyGridWorld/ChaseRunner.java      MyGridWorld/MyTermite.java \
MyGridWorld/CircleBug.java        MyGridWorld/Termite.java \
MyGridWorld/CircleBugRunner.java  MyGridWorld/TermiteRunner.java \
MyGridWorld/DiamondTermite.java   MyGridWorld/Termite.gif \
MyGridWorld/BlueBug.java          MyGridWorld/LifeRock.java \
MyGridWorld/BlueBugRunner.java    MyGridWorld/LifeRunner.java \
Cards/Card1.java  Cards/Card3.java      Cards/CardSoln3.java \
Cards/Card2.java  Cards/CardSoln2.java  Words.java  words.txt\

DEST = /home/downey/public_html/greent/thinkapjava/code

all:
	rsync -avp $(FILES) $(DEST)